title = Infdev
name = infdev
description = Infinite development, infinite possibilities.
author = jordan4ibanez
allowed_mapgens = singlenode
disabled_settings = enable_damage, creative_mode
min_minetest_version = 5.17-dev