name: Package Game

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout game
        uses: actions/checkout@v4

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Run Build Script
        run: haxe --run Packager

      - name: Upload Artifact
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: mod-package
          path: dist/*.zip
